const countries = [
  { name: "Австралия", checked: false },
  { name: "Австрия", checked: true },
  { name: "Беларусь", checked: true },
  { name: "Бельгия", checked: false },
  { name: "Великобритания", checked: true },
  { name: "Германия", checked: false },
  { name: "Израиль", checked: true },
  { name: "Испания", checked: false },
  { name: "Италия", checked: true },
  { name: "Канада", checked: false },
  { name: "Китай", checked: true },
  { name: "Франция", checked: false },
  { name: "Япония", checked: true },
  { name: "Индия", checked: false },
  { name: "Россия", checked: true },
  { name: "Швейцария", checked: false },
  { name: "Швеция", checked: true },
  { name: "Норвегия", checked: false },
  { name: "Австралия", checked: false },
  { name: "Австрия", checked: true },
  { name: "Беларусь", checked: true },
  { name: "Бельгия", checked: false },
  { name: "Великобритания", checked: true },
  { name: "Германия", checked: false },
  { name: "Израиль", checked: true },
  { name: "Испания", checked: false },
  { name: "Италия", checked: true },
  { name: "Канада", checked: false },
  { name: "Китай", checked: true },
  { name: "Франция", checked: false },
  { name: "Япония", checked: true },
  { name: "Индия", checked: false },
  { name: "Россия", checked: true },
  { name: "Швейцария", checked: false },
  { name: "Швеция", checked: true },
  { name: "Норвегия", checked: false },
];

export default countries;
